create table if not exists public.vet_knowledge_products (
  id bigint generated by default as identity primary key,
  canonical_name text not null unique,
  kind text not null check (kind in ('farmacia','alimento','accesorio','grooming','servicio_veterinario','insumo')),
  inventory_category text,
  active_ingredient text,
  therapeutic_class text,
  species text[] not null default '{}',
  aliases text[] not null default '{}',
  keywords text[] not null default '{}',
  requires_vet_review boolean not null default false,
  cold_chain boolean not null default false,
  lot_tracking boolean not null default false,
  metadata jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

alter table public.vet_knowledge_products enable row level security;
drop policy if exists "conocimiento veterinario lectura autenticada" on public.vet_knowledge_products;
create policy "conocimiento veterinario lectura autenticada" on public.vet_knowledge_products
for select to authenticated using (true);
grant select on public.vet_knowledge_products to authenticated;
revoke insert, update, delete on public.vet_knowledge_products from anon, authenticated;

create table if not exists public.vet_learning_aliases (
  id bigint generated by default as identity primary key,
  negocio_id uuid not null references public.negocios(id) on delete cascade,
  input_name text not null,
  normalized_input text not null,
  canonical_name text not null,
  classification text not null,
  inventory_category text,
  confirmed_by uuid default auth.uid(),
  confidence numeric(5,2) not null default 100,
  created_at timestamptz not null default now(),
  unique (negocio_id, normalized_input)
);
alter table public.vet_learning_aliases enable row level security;
drop policy if exists "aprendizaje por negocio leer" on public.vet_learning_aliases;
drop policy if exists "aprendizaje por negocio insertar" on public.vet_learning_aliases;
drop policy if exists "aprendizaje por negocio actualizar" on public.vet_learning_aliases;
drop policy if exists "aprendizaje por negocio eliminar" on public.vet_learning_aliases;
create policy "aprendizaje por negocio leer" on public.vet_learning_aliases for select to authenticated using (negocio_id = public.mi_negocio());
create policy "aprendizaje por negocio insertar" on public.vet_learning_aliases for insert to authenticated with check (negocio_id = public.mi_negocio() and confirmed_by = (select auth.uid()));
create policy "aprendizaje por negocio actualizar" on public.vet_learning_aliases for update to authenticated using (negocio_id = public.mi_negocio()) with check (negocio_id = public.mi_negocio());
create policy "aprendizaje por negocio eliminar" on public.vet_learning_aliases for delete to authenticated using (negocio_id = public.mi_negocio());
grant select, insert, update, delete on public.vet_learning_aliases to authenticated;
grant usage, select on sequence public.vet_learning_aliases_id_seq to authenticated;

create index if not exists vet_knowledge_kind_idx on public.vet_knowledge_products(kind);
create index if not exists vet_learning_negocio_idx on public.vet_learning_aliases(negocio_id, normalized_input);

insert into public.vet_knowledge_products
(canonical_name,kind,inventory_category,active_ingredient,therapeutic_class,species,aliases,keywords,requires_vet_review,cold_chain,lot_tracking)
values
('NexGard','farmacia','farmaco','afoxolaner','antiparasitario externo',array['perro'],array['nex gard','nexgar','nexgard chew'],array['pulga','garrapata','tableta masticable'],true,false,true),
('NexGard Spectra','farmacia','farmaco','afoxolaner + milbemicina oxima','antiparasitario interno y externo',array['perro'],array['nexgard spectra','nex gard spectra','nexgar spectra'],array['pulga','garrapata','gusano','tableta'],true,false,true),
('Bravecto','farmacia','farmaco','fluralaner','antiparasitario externo',array['perro','gato'],array['braveto','bravecto chew','bravecto spot on'],array['pulga','garrapata','tableta','pipeta'],true,false,true),
('Simparica','farmacia','farmaco','sarolaner','antiparasitario externo',array['perro'],array['simparica trio','simparika'],array['pulga','garrapata','tableta'],true,false,true),
('Frontline','farmacia','farmaco','fipronil','antiparasitario externo',array['perro','gato'],array['front line','frontline plus'],array['pulga','garrapata','pipeta','spray'],true,false,true),
('Revolution','farmacia','farmaco','selamectina','antiparasitario',array['perro','gato'],array['revolution plus','selamectin'],array['pipeta','pulga','acaro'],true,false,true),
('Drontal','farmacia','farmaco','praziquantel + pirantel','desparasitante interno',array['perro','gato'],array['drontal plus','drontel'],array['gusano','tableta','desparasitante'],true,false,true),
('Milbemax','farmacia','farmaco','milbemicina oxima + praziquantel','desparasitante interno',array['perro','gato'],array['milbe max'],array['gusano','tableta'],true,false,true),
('Amoxicilina veterinaria','farmacia','farmaco','amoxicilina','antibiótico',array['perro','gato'],array['amoxicillin','amoxivet'],array['antibiotico','infeccion'],true,false,true),
('Cefalexina veterinaria','farmacia','farmaco','cefalexina','antibiótico',array['perro','gato'],array['cephalexin','rilexine'],array['antibiotico','infeccion','piel'],true,false,true),
('Metronidazol veterinario','farmacia','farmaco','metronidazol','antimicrobiano',array['perro','gato'],array['metronidazole','flagyl vet'],array['diarrea','antimicrobiano'],true,false,true),
('Meloxicam veterinario','farmacia','farmaco','meloxicam','antiinflamatorio AINE',array['perro','gato'],array['metacam','meloxivet'],array['dolor','antiinflamatorio'],true,false,true),
('Prednisolona veterinaria','farmacia','farmaco','prednisolona','corticosteroide',array['perro','gato'],array['prednisone','prednisona'],array['inflamacion','alergia'],true,false,true),
('Vacuna antirrábica','farmacia','farmaco',null,'vacuna',array['perro','gato'],array['vacuna rabia','antirrabica','rabies vaccine'],array['vacuna','rabia','dosis'],true,true,true),
('Vacuna múltiple canina','farmacia','farmaco',null,'vacuna',array['perro'],array['vacuna quintuple','sextuple','octuple','dhpp'],array['vacuna','canina','dosis'],true,true,true),
('Vacuna triple felina','farmacia','farmaco',null,'vacuna',array['gato'],array['triple felina','fvrcp'],array['vacuna','felina','dosis'],true,true,true),
('Royal Canin','alimento','alimento',null,'nutrición',array['perro','gato'],array['royalcanin','royal canin veterinary'],array['alimento','croqueta','dieta'],false,false,true),
('Hill''s Pet Nutrition','alimento','alimento',null,'nutrición',array['perro','gato'],array['hills','science diet','prescription diet'],array['alimento','croqueta','dieta'],false,false,true),
('Purina Pro Plan','alimento','alimento',null,'nutrición',array['perro','gato'],array['proplan','purina proplan'],array['alimento','croqueta'],false,false,true),
('Pedigree','alimento','alimento',null,'nutrición',array['perro'],array['pedigri'],array['alimento','croqueta','perro'],false,false,true),
('Whiskas','alimento','alimento',null,'nutrición',array['gato'],array['wiskas'],array['alimento','gato'],false,false,true),
('Collar para mascota','accesorio','accesorio',null,'accesorio',array['perro','gato'],array['collar perro','collar gato'],array['collar','campana','accesorio'],false,false,false),
('Correa para mascota','accesorio','accesorio',null,'accesorio',array['perro','gato'],array['leash','correa perro'],array['correa','paseo','accesorio'],false,false,false),
('Arnés para mascota','accesorio','accesorio',null,'accesorio',array['perro','gato'],array['arnes','harness'],array['arnes','paseo','accesorio'],false,false,false),
('Shampoo veterinario','insumo','insumo',null,'higiene',array['perro','gato'],array['champu veterinario','shampoo mascota'],array['shampoo','baño','higiene'],false,false,true),
('Baño de grooming','grooming',null,null,'servicio de grooming',array['perro','gato'],array['baño pequeño','baño mediano','baño grande'],array['baño','grooming','pelaje'],false,false,false),
('Deslanado','grooming',null,null,'servicio de grooming',array['perro','gato'],array['de shedding','deshedding'],array['pelo','subpelo','grooming'],false,false,false),
('Consulta veterinaria','servicio_veterinario',null,null,'servicio clínico',array['perro','gato','otro'],array['consulta general','consulta vet'],array['consulta','veterinaria'],true,false,false),
('Hemograma','servicio_veterinario',null,null,'diagnóstico de laboratorio',array['perro','gato','otro'],array['cbc','conteo sanguineo'],array['laboratorio','sangre'],true,false,false),
('Profilaxis dental','servicio_veterinario',null,null,'procedimiento dental',array['perro','gato'],array['limpieza dental veterinaria'],array['dental','profilaxis'],true,false,false)
on conflict (canonical_name) do update set
  aliases=excluded.aliases, keywords=excluded.keywords, active_ingredient=excluded.active_ingredient,
  therapeutic_class=excluded.therapeutic_class, species=excluded.species,
  requires_vet_review=excluded.requires_vet_review, cold_chain=excluded.cold_chain,
  lot_tracking=excluded.lot_tracking, updated_at=now();
